import {PRIMARY_600} from '@darta-styles'

export const createArtworkStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '95%',
    border: '1px solid #eaeaea',
    alignSelf: 'center',
    borderRadius: '0.5vw',
    gap: '2vh',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    '@media (min-width: 800px)': {
      width: '95%',
      gap: '5vh',
    },
  },
  backButton: {
    color: PRIMARY_600,
    alignSelf: 'flex-start',
    m: 2,
  },
  imageArtworkContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignContent: 'center',
    alignItems: 'center',
    minWidth: '50%',
    '@media (min-width: 700px)': {
      width: '100%',
      flexDirection: 'row',
    },
  },
  inputTextContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    gap: '2vh',
    alignItems: 'center',
    alignContent: 'center',
    width: '100%',
  },
  displayTextContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2vh',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  imageContainer: {
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignContent: 'center',
    maxWidth: '40vw',
    minHeight: '100%',
    '@media (min-width: 780px)': {
      minHeight: '45vh',
    },
  },
  defaultImageEdit: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: '40vw',
    '@media (min-width: 780px)': {
      minHeight: '45vh',
    },
    alignSelf: 'center',
  },
  defaultImage: {
    marginTop: '1em',
    width: '100%',
    maxHeight: '39vh',
    alignSelf: 'center',
    borderWidth: 30,
  },
  inputText: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    m: 2,
  },
  saveButtonContainer: {
    alignSelf: 'center',
    m: 2,
    display: 'flex',
    gap: '2vw',
    width: '90%',
    justifyContent: 'space-between',
  },
  multiLineContainer: {
    my: 2,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: '10vh',
    height: '100%',
    width: '90%',
    '@media (max-width: 780px)': {
      flexDirection: 'column',
    },
  },
  dimensionsAndPricingContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignContent: 'center',
    alignItems: 'center',
    minWidth: '50%',
  },
};
