import {PRIMARY_BLUE, PRIMARY_DARK_GREY} from '../../../styles';

export const profileStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    gap: '5vh',
    minWidth: '80vw',
    minHeight: '100vh',
    mt: '10vh',
    alignSelf: 'center',
  },
  profile: {
    galleryInfoContainer: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      gap: '5%',
      minWidth: '80vw',
      alignSelf: 'center',
      '@media (max-width: 800px)': {
        flexDirection: 'row',
        justifyContent: 'flex-start',
      },
    },
    imageBox: {
      height: 400,
      width: 400,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignSelf: 'center',
      textAlign: 'center',
      '@media (max-width: 800px)': {
        height: 200,
        width: 200,
      },
    },
    galleryDetails: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-around',
      alignItems: 'center',
      alignSelf: 'center',
      width: '80%',
    },
    editButtonProfile: {
      color: PRIMARY_BLUE,
      alignSelf: 'flex-end',
    },
    galleryHeaderContainer: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignSelf: 'flex-start',
      height: '40%',
      width: '100%',
      '@media (max-width: 790px)': {
        flexDirection: 'column',
      },
    },
    galleryLocationContainer: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-around',
      gap: '5%',
      width: '80%',
      mt: 3,
    },
    galleryBioContainer: {
      display: 'flex',
      m: 3,
      flexDirection: 'column',
      justifyContent: 'flex-start',
      height: '0%',
    },
    galleryAddressContainer: {
      display: 'flex',
      flexDirection: 'column',
      width: '100%',
      alignItems: 'center',
      alignText: 'center',
    },
    galleryBioStyles: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'center',
      width: '100%',
      textAlign: 'center',
      color: PRIMARY_DARK_GREY,
    },
    defaultImage: {
      marginTop: '1em',
      maxWidth: '100%',
      borderWidth: 30,
    },
    addressText: {
      alignText: 'center',
      color: PRIMARY_DARK_GREY,
    },
  },
  edit: {
    backButton: {
      color: PRIMARY_BLUE,
      alignSelf: 'flex-start',
    },
    inputTextContainer: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      gap: '1vh',
      alignItems: 'center',
      minHeight: '10vh',
      width: '100%',
    },
    inputText: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      minHeight: '10vh',
      width: '100%',
    },
    saveButton: {
      color: PRIMARY_BLUE,
      alignSelf: 'flex-end',
    },
  },
};
