import {PRIMARY_BLUE, PRIMARY_DARK_GREY, PRIMARY_GREY} from '../../../styles';

export const profileStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    gap: '5%',
    minWidth: '70vw',
    minHeight: '100vh',
    mb: 5,
    alignSelf: 'center',
  },
  imageBox: {
    height: 400,
    width: 400,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignContent: 'center',
    textAlign: 'center',
  },
  imageBoxEdit: {
    height: 400,
    width: 400,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignContent: 'center',
    textAlign: 'center',
    cursor: 'pointer',
  },
  editButtonProfile: {
    color: PRIMARY_BLUE,
    alignSelf: 'flex-start',
  },
  editButtonEdit: {
    color: PRIMARY_BLUE,
    alignSelf: 'flex-end',
  },
  uploadImageContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: '5%',
    alignItems: 'center',
  },
  typographyTitle: {
    fontFamily: 'EB Garamond',
    color: PRIMARY_BLUE,
    fontSize: '2rem',
    my: '3vh',
    '@media (min-width:800px)': {
      fontSize: '2.5rem',
    },
    cursor: 'default',
  },
  typography: {
    fontFamily: 'EB Garamond',
    color: PRIMARY_DARK_GREY,
    fontSize: '1rem',
    '@media (minWidth: 800px)': {
      fontSize: '1.3rem',
    },
    cursor: 'default',
  },
  button: {
    color: PRIMARY_BLUE,
  },
  inputTextContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: '1vh',
    alignItems: 'center',
    minHeight: '10vh',
    width: '100%',
  },
  inputText: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: '10vh',
    width: '100%',
    // border: '1px solid black',
  },
  formTextField: {
    width: '95%',
    margin: 2,
    fontSize: '2rem',
  },
  helpIcon: {
    color: PRIMARY_GREY,
  },
  editTextField: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    minHeight: '10vh',
  },
  defaultImageContainer: {marginTop: '1em', maxWidth: '100%', borderWidth: 30},
  displayNone: {
    display: 'none',
  },

  galleryHeaderContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'flex-start',
    alignItems: 'center',
    gap: '5%',
    height: '40%',
    width: '95%',
  },
  galleryBioContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    height: '0%',
  },
  galleryDetails: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'left',
    width: '60%',
  },
  galleryLocationContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: '5%',
    mt: 3,
  },
  galleryAddressContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  galleryBioStyles: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
    textAlign: 'center',
    color: PRIMARY_DARK_GREY,
  },
  divider: {
    width: '100%',
    maxWidth: 360,
    bgcolor: PRIMARY_DARK_GREY,
  },
  defaultImage: {
    marginTop: '1em',
    maxWidth: '100%',
    borderWidth: 30,
  },
  submitForm: {
    alignSelf: 'center',
  },
};
