FROM node:18-alpine

ENV NODE_ENV=development

WORKDIR /app

COPY ./packages/next/package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json ./packages/next/tsconfig.json ./

COPY ./packages/next ./packages/next
COPY ./packages/components ./packages/components

RUN npm install -g pnpm
RUN pnpm install

EXPOSE 8000
ENTRYPOINT [ "pnpm", "next", "dev" ]