fetch('https://www.revolve.com/r/ajax/GetProductData.jsp?product%5B%5D=AGOL-WF7', {
  headers: {
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
    'accept-language': 'en-US,en;q=0.5',
    'cache-control': 'max-age=0',
    'sec-ch-ua': '"Chromium";v="110", "Not A(Brand";v="24", "Brave";v="110"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'sec-gpc': '1',
    'upgrade-insecure-requests': '1',
    cookie: 'currency=USD; viewNumR1=100; isPopupEnabledR1=true; pocketViewR1=front; currencyOverride=USD; userLanguagePref=en; fontsLoaded=1; remarketing=TypeB; altexpneedlog=true; userClosedNtfDialogCount=1; userLastSeenNtfDialogDate=2023-02-13; userSeenNtfDialogDate=2023-02-13; GA_encodeUtmz=null; GA_encodeUtma=null; product-zoom-appeared=true; name.cookie.ntf.no.ribbon=true; sortByR2=featured; ntfPopupSuppressionCount=5; JSESSIONID2=5EF71766C81E7B58624B4BA9BCB5649B.tc-ibuki_tomcat2; __cf_bm=nTCT03889nADWsqcoPhbOVlvw.SXkUQ6Oest0kPMNp0-1676336698-0-AabtpP6ZmuiCtcKbZaWCJ5Ep5V39iGSNS8NQ39/pr9GStXPSF3mtvHpiPQ/rxVHAwohwVaquE1/BJ3lKjKjK5Gk=; name.cookie.last.visited.product=ASTR-WD190; bb_PageURL=%2Fcontent%2Fproduct%2Fpdp-content%2FASTR-WD190%2FsimilarItems%3Fd%3DWomens; browserID=FrHYDakqApLWqGIwPbh92DQh5OWnHy',
  },
  referrerPolicy: 'strict-origin-when-cross-origin',
  body: null,
  method: 'GET',
}).then((results) => console.log(results));
