apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: my-ingressroute
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - match: Host(`darta.works`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: next
      namespace: darta-next
      port: 1169
  - match: Host(`www.darta.works`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: next
      namespace: darta-next
      port: 1169
  tls:
    secretName: my-tls-secret
