apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: minio-operator
    meta.helm.sh/release-namespace: minio
  creationTimestamp: "2023-09-18T18:24:01Z"
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v5.0.9
    helm.sh/chart: operator-5.0.9
  name: console
  namespace: minio
  resourceVersion: "1442815"
  uid: 2aae1397-3fae-46c5-8d75-3213541fd51a
spec:
  clusterIP: 10.8.6.11
  clusterIPs:
  - 10.8.6.11
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 32766
  - name: https
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: minio-operator-console
    app.kubernetes.io/name: operator
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
