apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: minio-operator
    meta.helm.sh/release-namespace: minio-operator
  creationTimestamp: "2023-08-31T14:13:55Z"
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v5.0.7
    helm.sh/chart: operator-5.0.7
  name: console
  namespace: minio-operator
  resourceVersion: "289740"
  uid: 4fdc7231-8585-466f-860a-3aa2d8ce0e27
spec:
  clusterIP: 10.96.106.218
  clusterIPs:
    - 10.96.106.218
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 9000
    - name: https
      port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/instance: minio-operator-console
    app.kubernetes.io/name: operator
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
