import {PRIMARY_BLUE, PRIMARY_MILK} from '../../../styles';

export const createArtworkStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '95%',
    border: '1px solid #eaeaea',
    alignSelf: 'center',
    borderRadius: '0.5vw',
    backgroundColor: PRIMARY_MILK,
    gap: '2vh',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    '@media (min-width: 800px)': {
      width: '95%',
      gap: '5vh',
    },
  },
  backButton: {
    color: PRIMARY_BLUE,
    alignSelf: 'flex-start',
    m: 2,
  },
  imageArtworkContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignContent: 'center',
    alignItems: 'center',
    minWidth: '50%',
    '@media (min-width: 700px)': {
      width: '100%',
      flexDirection: 'row',
    },
  },
  dimensionsAndPricingContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignContent: 'center',
    alignItems: 'center',
    width: '90%',
    gap: '2rem',
    height: '100%',
    '@media (min-width: 780px)': {
      maxWidth: '90%',
    },
  },
  artworkDetailsContainer: {
    width: '80%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    gap: '2rem',
    justifyContent: 'center',
    '@media (min-width: 780px)': {
      maxWidth: '90%',
    },
  },
  inputTextContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignContent: 'center',
  },
  imageContainer: {
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignContent: 'center',
    maxWidth: '40vw',
    minHeight: '100%',
    '@media (min-width: 780px)': {
      minHeight: '45vh',
    },
  },
  imageContainerExhibitions: {
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignContent: 'center',
    maxWidth: '40vw',
    minHeight: '100%',
    '@media (min-width: 780px)': {
      minHeight: '30vh',
    },
  },
  defaultImageEdit: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: '40vw',
    '@media (min-width: 780px)': {
      minHeight: '45vh',
    },
    alignSelf: 'center',
  },
  defaultImage: {
    marginTop: '1em',
    width: '100%',
    maxHeight: '39vh',
    alignSelf: 'center',
    borderWidth: 30,
  },
  inputText: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    width: '90%',
    m: 2,
  },

  saveButtonContainer: {
    alignSelf: 'center',
    alignContent: 'center',
    display: 'flex',
    gap: '2vw',
    width: '90%',
    mb: 2,
    justifyContent: 'space-around',
  },
  multiLineContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    minHeight: '10vh',
    height: '100%',
    width: '100%',
    '@media (max-width: 780px)': {
      flexDirection: 'column',
    },
  },
};
