import * as Colors from '@darta-styles'

export const createArtworkStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '95%',
    border: '1px solid #eaeaea',
    alignSelf: 'center',
    borderRadius: '0.5vw',
    backgroundColor: Colors.PRIMARY_50,
    gap: '2vh',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    '@media (min-width: 1280px)': {
      width: '95%',
      gap: '5vh',
    },
  },
  backButton: {
    color: Colors.PRIMARY_600,
    alignSelf: 'flex-start',
    m: 2,
  },
  imageArtworkContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignContent: 'center',
    alignItems: 'center',
    minWidth: '50%',
    '@media (min-width: 1280px)': {
      width: '100%',
      flexDirection: 'row',
    },
  },
  dimensionsAndPricingContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignContent: 'center',
    alignItems: 'center',
    width: '90%',
    gap: '2rem',
    height: '100%',
    '@media (min-width: 1280px)': {
      maxWidth: '90%',
    },
  },
  artworkDetailsContainer: {
    width: '80%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    gap: '2rem',
    justifyContent: 'center',
    '@media (min-width: 1280px)': {
      maxWidth: '90%',
    },
  },
  inputTextContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignContent: 'center',
  },
  imageContainer: {
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    maxWidth: '85vw',
    gap: '1vh',
    minHeight: '100%',
    '@media (min-width: 1280px)': {
      height: '40vh',
      width: '100%',
    },
  },
  imageContainerExhibitions: {
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignContent: 'center',
    maxWidth: '40%',
    minHeight: '100%',
    '@media (min-width: 1280px)': {
      minHeight: '30vh',
    },
  },
  defaultImageEdit: {
    maxHeight: '40vh',
    maxWidth: '40vw',
    '@media (min-width: 1280px)': {
      maxHeight: '100%',
      maxWidth: '100%',
    },
  },
  defaultImageContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    margin: '1em',
  },
  defaultImage: {
    p: '1em',
    // width: '100%',
    maxHeight: '38vh',
    maxWidth: '38vw',
    alignSelf: 'center',
    // borderWidth: 30,
  },
  inputText: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    width: '90%',
    m: 2,
  },

  saveButtonContainer: {
    alignSelf: 'center',
    alignContent: 'center',
    display: 'flex',
    gap: '2vw',
    width: '90%',
    mb: 2,
    justifyContent: 'space-around',
  },
  multiLineContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    height: '100%',
    width: '95%',
    gap: '5vh',
    mt: '1em',
    '@media (max-width: 1280px)': {
      gap: '3vh',
      flexDirection: 'column',
    },
  },
};
