name: Deploy with DevSpace

on:
  push:
    tags:
      - 'next-*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Node.js (if using a Node.js package)
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Modify the version as required

    - name: Install DevSpace CLI
      run: curl -s -L "https://get.devspace.sh" | bash

    - name: Navigate to the package
      run: cd packages/next # Change the path to the package you want to deploy

    - name: Deploy using DevSpace
      run: devspace deploy
