name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4] # number of containers to run tests in
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true # enable Cypress Dashboard recording
          parallel: true # enable parallelization
          group: 'Group Name' # name of the group the test run belongs to
          build: pnpm run build
          start: pnpm start
          browser: chrome
          config-file: cypress.json
          tag: ${{ github.event_name }},${{ github.ref }}
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
