name: Cypress Tests
on: [push]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/next
    
      - name: Set up environment variables
        run: |
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_API_KEY }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_AUTH_DOMAIN }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_PROJECT_ID=${{ secrets.NEXT_PUBLIC_REACT_APP_PROJECT_ID }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_STORAGE_BUCKET }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_SENDER_ID=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_SENDER_ID }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_APP_ID }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_MEASUREMENT_ID }} >> packages/next/.env
            echo NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }} >> packages/next/.env

      - name: Build app
        run: pnpm --prefix ./packages/next run build

      - name: Cypress run e2e
        uses: cypress-io/github-action@v5
        with:
          start: pnpm --prefix ./packages/next start
          wait-on: 'http://localhost:3000'
          command: pnpm --prefix ./packages/next run cy-e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/next
    
      - name: Set up environment variables
        run: |
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_API_KEY }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_AUTH_DOMAIN }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_PROJECT_ID=${{ secrets.NEXT_PUBLIC_REACT_APP_PROJECT_ID }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_STORAGE_BUCKET }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_SENDER_ID=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_SENDER_ID }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_APP_ID }} >> packages/next/.env
            echo NEXT_PUBLIC_REACT_APP_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_REACT_APP_FIREBASE_MEASUREMENT_ID }} >> packages/next/.env
            echo NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }} >> packages/next/.env

      - name: Build app
        run: pnpm --prefix ./packages/next run build

      - name: Cypress run component
        uses: cypress-io/github-action@v5
        with:
          start: pnpm --prefix ./packages/next start
          wait-on: 'http://localhost:3000'
          command: pnpm --prefix ./packages/next run cy-component
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
